### ISSUE TITLE
Review upload workflow

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#102]
We want to allow people to upload `n` pages of a leaflet, but it can be a bit confusing going through all the steps. Some basic research on how people find the upload process would be great, but failing that (in this time frame) just thinking about the workflow a bit more would be useful.

Also, the upload wizard isn't lovely code, so it might be a pain to change :(

**Comment by tam-borine** [comment]
On the subject of upload flow, I noticed that if I try to Submit an upload without a back page to leaflet, I am stopped with the message 'please add a photo or skip this step'. There is no obvious 'skip' button in sight, I gather it is 'no more pages'. That's a little confusing so either changing the validation message to 'please add a photo or skip by clicking the 'no more pages'' button or changing the button label to Skip. An even better change would be, in my opinion, to remove the validation altogether and assume that if the user is Submits the upload without a back page then they just don't want a back page. I think it's a safe assumption that would improve user flow.
