### ISSUE TITLE
Make this the canonical repo

### ISSUE THREAD

**Issue by boffbowsh** [DemocracyClub/electionleaflets#127]
It seems that upstream is no longer maintained and this is the canonical repo. Transferring ownership to this fork would make raising Pull Requests easier, especially for org members

**Comment by chris48s** [comment]
..or just hostile-fork it like the OAF did with theirs:
https://github.com/openaustralia/electionleaflets

**Comment by boffbowsh** [comment]
@symroe would you be able to do this please? You just need to [Contact Github](https://github.com/contact) and ask them to orphan this repo from its fork.

**Comment by symroe** [comment]
Done
