### ISSUE TITLE
remove candidates picker

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/electionleaflets#141]
Realistically we're not going to provide useful candidate options for `local.2018-05-03` but it would be nice to still be able to capture leaflets (even if they don't have much useful meta-data). It would probably be better user experience to just remove the candidate picker.

**Comment by symroe** [comment]
We sort of did this already. Marking as closed as this issue isn't helpful any more in the context of more major refactoring work (and the fact the site isn't online, so _that's fixed the issue_?!)
