### ISSUE TITLE
Increase upload file size

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#165]
I have a phone that's a couple of years old and takes 13MP photos by default.

With that file size, I get a hard error that the uploaded file size to too high. I expect this would be common for anyone with a newish phone with a decent camera.

Can we push the file size limit up to something fairly high?

I'm not sure at what stage in the stack we'd need to do this, but FWIW I got what looked like a Lambda error in JSON rather than a Django form validation error.

**Comment by willsheppard** [comment]
One approach for this is to allow large uploads, but resize the image on the backend and only store a smaller size.

**Comment by symroe** [comment]
We're using AWS Lambda to host this project, but they limit the POST size to 5MB.

This is now closed by using JavaScript to upload large file sizes, and as you suggest, resize later.
