### ISSUE TITLE
Upgrade to Django 2.2 (or latest LTS)

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#184]

**Comment by chris48s** [comment]
The plan for this was:
- Get on to django 1.11 (the last django release to allow python 2.7)
- Upgrade from python 2.7 to python 3
- Upgrade from django 1.11 to django 2(.2)

Step one of that got done in https://github.com/DemocracyClub/electionleaflets/pull/149 but the python 2 to 3 migration is outstanding and will need to happen first.
