### ISSUE TITLE
Automatically tweet leaflets

### ISSUE THREAD

**Issue by EmilyLRandall** [DemocracyClub/electionleaflets#28]
https://twitter.com/electionspotter

**Comment by symroe** [comment]
The feed is fixed now, but really EL should tweet directly.

**Comment by andylolz** [comment]
IFTTT doesn’t seem to offer a way to embed images linked in RSS enclosures. Weak! Would also be nice to stagger tweets rather than hammer loads at once (when IFTTT runs).

Because of these IFTTT issues, would a more customisable bot (e.g. on heroku) be preferable?

**Comment by rossjones** [comment]
Perhaps IFTTT/Zapier -> http://bufferapp.com ?

**Comment by symroe** [comment]
Feed updated to include the image URL in the description.  Trying it out to see if that's going to fix it using IFTTT.  Failing that, we'll just have to use the twitter API directly

**Comment by symroe** [comment]
Update: IFTTT sucks.  Let's do this manually – that way we get rid of the IFTTT tracker URLs too.
