### ISSUE TITLE
Implement elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#33]

**Comment by rossjones** [comment]
What would this contain? Is it just a simple container for leaflets?

How about:

 * name
 * url - for more information
 * date range - when it 'starts' to voting day
 * hashtag - for when sharing

so something like ...

UK General Election 2015
http://en.wikipedia.org/wiki/United_Kingdom_general_election,_2015
30/03/2015 - 07/05/2015
#ge2015 

Aside: Do UK elections have a canonical url anywhere?
