### ISSUE TITLE
Latest leaflets feed broken?

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/electionleaflets#38]
https://electionleaflets.org/feeds/latest/ is currently showing:

![screen shot 2015-03-24 at 01 48 19](https://cloud.githubusercontent.com/assets/464193/6794282/d81420d2-d1c7-11e4-8770-98a1bd61236e.png)

**Comment by rossjones** [comment]
Looks okay right now.  The enclosures are missing useful info, but apart from that ...

**Comment by andylolz** [comment]
Cool
