### ISSUE TITLE
Strip EXIF data from images and store on model

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#40]
Strip all EXIF data apart from the rotation tag.

**Comment by JustinWingChungHui** [comment]
I was having a look at this.  Do you think we should use gexiv2 for this?

**Comment by symroe** [comment]
I think this is a fairly high priority to remove from the public images. However I also think we should store the exif data on the image model – it might be useful later for us, for example in the rotation or data taken fields.

**Comment by kirknorthrop** [comment]
I was planning on having a look at this.

**Comment by hugovk** [comment]
Here's a few options: http://stackoverflow.com/questions/19786301/python-remove-exif-info-from-images
