### ISSUE TITLE
Link to constiuency bottom of the leaflet page does not work

### ISSUE THREAD

**Issue by Bjwebb** [DemocracyClub/electionleaflets#63]
e.g. on a page like https://electionleaflets.org/leaflets/10732/

I think the leaflet map is placing a layer over this that makes the link not respond when I hover over / click on it.

**Comment by Bjwebb** [comment]
When I inspect the page with Chrome's Developer tools, I can see that there is a div (created by JS) which fills the entire leaflet_map section, "on top of" the constituency link.

The problem goes away if I wrap the leaflet_map div in an extra parent, e.g. if I replace

```html
<div id="leaflet_map"></div>
```

with

```html
<div>
<div id="leaflet_map"></div>
</div>
```

(this appears to be because the JS created div now only fills the new div parent, instaed of the entire section)

**Comment by andylolz** [comment]
@Bjwebb: Ace! That fix looks exactly correct to me :) And that template is the correct one. Can you send it as a pull request? Thanks!
