### ISSUE TITLE
Green party emblem not working on leaflet pagews

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#66]
_From @goatchurchprime on April 28, 2015 6:55_

eg https://electionleaflets.org/leaflets/11217/

The image links to a non-existent file:
http://openelectoralcommission.org.uk/party_images/Emblem_1119.jpg

On the other hand, libdems get this:
http://openelectoralcommission.org.uk/party_images/Emblem_106.gif

_Copied from original issue: electionleaflets/electionleaflets#32_

**Comment by symroe** [comment]
_From @andylolz on April 28, 2015 7:35_

This is a duplicate of DemocracyClub/electionleaflets#62.

**Comment by andylolz** [comment]
Good point, me! Closing as duplicate.
