### ISSUE TITLE
Election Leaflets Analysis - Data Export & Top Line Figures

### ISSUE THREAD

**Issue by EmilyLRandall** [DemocracyClub/electionleaflets#82]
Total number of leaflets per party included in analysis then Per Party (primarily top 7) number of leaflets with:

Pictures of sending party leader
Mentions of sending party leader
Party logo
Pictures of opposition of party leader
Mentions of opposition of party leader
Squeeze messages
Graph included 
no.s of leaflets per style i.e. newspaper, leaflets

Or being able to fully export, and the data is further analysed manually.

**Comment by symroe** [comment]
https://electionleaflets.org/analysis/reports/analysis/per_party/
