### ISSUE TITLE
Postcode L39 6RW not working?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/electionleaflets#91]
>I am trying to send a new election leaflet, attached, but I am blocked by repeatedly being told to enter a valid postcode which I have done, L39 6RW. What is wrong with your system?

**Comment by JoeMitchell** [comment]
And also

> HP22 5UQ

**Comment by philipjohn** [comment]
Same for WS13 6SG so perhaps validation is more fundamentally broken somewhere?

**Comment by hubgit** [comment]
Is it possible that the API key is hitting a limit? A postcode that wasn't working yesterday is now working today, and I can't see anything in the code that looks wrong, where it fetches data from the MapIt API.

**Comment by boffbowsh** [comment]
Likely a transient issue or rate limiting, all the mentioned postcodes work fine now
