### ISSUE TITLE
Test mobile upload on different phones

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#97]
The camera upload part doesn't work on Android / Firefox, so I expect it's broken on other browsers / OSs too. We need someone who knows about mobile JS development to review the upload process, really.

**Comment by tam-borine** [comment]
So on iOS 6s (Safari, Chrome, Firefox) we get a 500 when Submitting upload
@requires_csrf_token
def server_error(request, template_name='500.html')

**Comment by tam-borine** [comment]
But on iOS 5s (Safari, Chrome, Firefox) it seems to work fine. I'm going to double check this is the case and then move on to Androids

**Comment by tam-borine** [comment]
So Android Nexus 5x also has errors when submitting the uploaded photo, on Chrome, also server side, but this time from Heroku. Says we can check
$ heroku logs

**Comment by tam-borine** [comment]
Can't even hit the url, electionleaflets-staging.herokuapp.com, on Firefox Android Nexus 5x

**Comment by tam-borine** [comment]
There seems to be some out of memory related errors which may be only on the staging url.
Steps to reproduce:
1. start watching real time logs with $ heroku logs --tail
2. get a mobile (record the model, version and browser) and go to www.electionleaflets-staging.herokuapp.com, you should see logs updating as you make the GET
3. step through the UI motions of uploading a photo, watch the logs on the final Submit (after representative is chosen).
4. You'll see  Error R14 (Memory quota exceeded), if it works afterwards, great you got a flaky positive. If it does not you will get Error R15 (Memory quota vastly exceeded) followed by SIGKILL, crashing and error code is https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response
