### ISSUE TITLE
Serve images over HTTPS

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#99]
This will stop the mixed context warnings on the site.

**Comment by boffbowsh** [comment]
Steps to do this, all require some sort of elevated privilege so something for @symroe most likely:

Assuming you can receive email at `{administrator,webmaster,postmaster,admin,hostmaster}@electionleaflets.org` or francis@flourish.org:

1. Log in to AWS console and be in the us-east-1 region
2. Go to https://console.aws.amazon.com/acm/home?region=us-east-1
3. Follow the steps to validate ownership of `data.electionleaflets.org`
4. Go to https://console.aws.amazon.com/cloudfront/home?region=us-east-1
5. Create a new CloudFront distribution pointing at the data.electionleaflets.org S3 bucket
6. Select the ACM certificate from the Custom SSL Certificate dropdown and choose the SNI option
7. Wait for the distribution to be enabled, test it with `curl -H 'Host: data.electionleaflets.org' https://d1234567890abcdef.cloudfront.net/path/to/some/leaflet.jpg`
8. Point the DNS at the distribution host as a CNAME and wait for it to propogate
9. Change `MEDIA_URL` in the production `settings/local.py` and restart

If you don't have access to receive email at those addresses we can do some Lets Encrypt stuff instead.

**Comment by symroe** [comment]
Thanks, the above has now been done!
